# 🐻‍❄️🔮 Noelware's Helm Charts: Curated catalog of Noelware's Helm charts.
# Copyright (c) 2022-2024 Noelware, LLC. <team@noelware.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

## @section Global Parameters
## @descriptionStart
## Contains any global parameters that will affected all objects in the JetBrains YouTrack Helm chart.
## @descriptionEnd
##
## @param global.replicas Amount of replicas to use
## @param global.resources Resource list to apply to all containers.
## @param global.fullNameOverride String to fully override the Helm installation name for all objects
## @param global.nameOverride String to override the Helm installation name for all objects, will be in conjunction with a prefix of `<install-name>-`
## @param global.clusterDomain Domain host that maps to the cluster
## @param global.nodeSelector Selector labels to apply to contraint the pods to specific nodes. Read more in the [Kubernetes documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector).
## @param global.tolerations List of all taints/tolerations to apply in conjunction with `global.affinity`. Read more in the [Kubernetes documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration)
## @param global.affinity Map of all the affinity to apply to the spawned Pods. Read more in the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/).
## @param global.annotations Map of annotations to append to on all objects that this Helm chart creates.
## @param global.extraEnvVars List of extra environment variables to append to all init/sidecar containers and normal containers.
## @param global.initContainers List of init containers to create.
## @param global.podSecurityContext Security context for all spawned Pods. Read more in the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
## @param global.containerSecurityContext Security context for all init, sidecar, and normal containers. Read more in the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).
## @param global.dnsPolicy DNS policy for the pod.
## @param global.dnsConfig Configures the [DNS configuration](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config) for the pod.
## @param global.baseUrl Base URL to use when configuring the YouTrack server
global:
  replicas: 1
  fullNameOverride: ""
  nameOverride: ""
  clusterDomain: cluster.local
  nodeSelector: {}
  tolerations: []
  affinity: {}
  annotations: {}
  extraEnvVars: []
  initContainers: []
  podSecurityContext: {}
  containerSecurityContext: {}
  baseUrl: ""
  dnsPolicy: ""
  dnsConfig: {}
  resources: {}
    ## Example:
    ##  limits:
    ##    memory: 2Gi
    ##    cpu: 1500m
    ##  requests:
    ##    memory: 512Mi
    ##    cpu: 150m

## @section Docker Image Parameters
## @descriptionStart
## Parameters to modify the Docker image that is ran.
## @descriptionEnd
##
## @param image.pullPolicy [string] [Pull policy](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy) when pulling the image.
## @param image.registry Registry URL to point to. For Docker Hub, use an empty string.
## @param image.image Image name.
## @param image.tag The tag of the image. Keep this as a empty string if you wish to use the default app's version.
## @param image.digest Digest in the form of `<alg>:<hex>`, this will replace the `image.tag` property if this is not empty.
image:
  pullPolicy: IfNotPresent
  registry: "" # keep empty to use docker hub
  image: jetbrains/youtrack
  tag: "" # keep empty for the app version
  digest: ""

## @section Service Account Parameters
## @param serviceAccount.create Whether or not if the service account should be created for this Helm installation.
## @param serviceAccount.annotations Any additional annotations to append to this ServiceAccount
## @param serviceAccount.name The name of the service account, this will be the Helm installation name if this is empty.
serviceAccount:
  create: true
  annotations: {}
  name: ""

## @section Deployment Parameters
## @param deployment.configureFlags List of [JVM configuration flags](https://www.jetbrains.com/help/youtrack/server/configure-jvm-options.html#set-jvm-options) to use when configuring the installation of your YouTrack server.
## @param deployment.strategy The [Deployment strategy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy) when creating the deployment.
deployment:
  configureFlags: "-J-Dorg.eclipse.jetty.server.Request.maxFormKeys=10000 -J-Xmx1024m"
  strategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0

## @section Persistence
## @param persistence.accessModes List of access modes when creating the Persistent Volume Claim
## @param persistence.storageClass StorageClass for the PVC creation
## @param persistence.existingClaims.backups If there is any existing backup PVC, then this is where you reference it.
## @param persistence.existingClaims.data If there is any existing data PVC, then this is where you reference it.
## @param persistence.existingClaims.logs If there is any existing logs PVC, then this is where you reference it.
## @param persistence.existingClaims.conf If there is any existing config PVC, then this is where you reference it.
## @param persistence.selectors.backups Mapping of the [selectors](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector) to filter when creating the backups PVC.
## @param persistence.selectors.data Mapping of the [selectors](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector) to filter when creating the data PVC.
## @param persistence.selectors.conf Mapping of the [selectors](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector) to filter when creating the conf PVC.
## @param persistence.selectors.logs Mapping of the [selectors](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector) to filter when creating the logs PVC.
## @param persistence.sizes.backups Size of the backups PVC
## @param persistence.sizes.data Size of the data PVC
## @param persistence.sizes.logs Size of the logs PVC
## @param persistence.sizes.conf Size of the config PVC
persistence:
  accessModes: [ReadWriteOnce]
  storageClass: ""
  existingClaims:
    backups: ""
    logs: ""
    data: ""
    conf: ""
  selectors:
    backups: {}
    logs: {}
    data: {}
    conf: {}
  sizes:
    backups: 10Gi
    data: 10Gi
    logs: 5Gi
    conf: 512Mi

## @section Service Parameters
## @descriptionStart
## Parameters to configure a [Kubernetes service](https://kubernetes.io/docs/concepts/services-networking/service/) to allow external connections to your
## YouTrack instance.
## @descriptionEnd
##
## @param service.clusterIP IP to use for the cluster IP if `type` is `ClusterIP`.
## @param service.enabled Whether or not if a Kubernetes service should be enabled.
## @param service.type The [service type](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types) to use.
## @param service.selectorLabels Selector to apply this Kubernetes service to
## @param service.port The port that YouTrack will listen on.
## @param service.externalName If `service.type` == `"ExternalName"`, then this would be set as [`spec.externalName`](https://kubernetes.io/docs/concepts/services-networking/service/#externalname)
## @param service.loadBalancer If `service.type` == `"LoadBalancer"`, then this would be set as [`status.loadBalancer`](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer)
service:
  enabled: true
  type: ClusterIP
  selectorLabels: {}
  port: 8080
  clusterIP: ""
  externalName: ""
  loadBalancer: {}

## @section Ingress
## @descriptionStart
## [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress) configuration.
## @descriptionEnd
##
## @param ingress.className Ingress class name to use.
## @param ingress.enabled Whether if Ingress record generation should be enabled or not.
## @param ingress.pathType Whatever [path type](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) to use.
## @param ingress.hostname Default host for the Ingress record.
## @param ingress.path Default path for the Ingress record.
## @param ingress.annotations Additional annotations for the Ingress record. To enable certificate autogeneration, place the `cert-manager` annotations here.
## @param ingress.extraPaths List of extra paths to add to the Ingress record.
## @param ingress.extraRules Any extra rules to add to the Ingress record.
ingress:
  enabled: false
  pathType: ImplementationSpecific
  hostname: youtrack.local
  className: ""
  path: /
  annotations: {}
  extraPaths: []
  extraRules: []

## @section Pod Disruption Budget
## @param podDisruptionBudget.enabled Enables the use of a `PodDisruptionBudget`. Read more in the [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/pods/disruptions)
## @param podDisruptionBudget.minAvailable Minimum number (or percentage) of pods that should be remained scheduled
## @param podDisruptionBudget.maxUnavailable Maximum number (or percentage) of pods that maybe made unavaliable.
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  maxUnavailable: null

## @section Subcharts
external:
  ## @section JetBrains Hub
  ## @param external.hub.enabled whether or not if the JetBrains Hub chart by Noelware should also be used.
  hub:
    enabled: false
