{{/*
~ 🐻‍❄️🔮 Noelware's Helm Charts: Curated catalog of Noelware's Helm charts.
~ Copyright (c) 2022-2024 Noelware, LLC. <team@noelware.org>
~
~ Permission is hereby granted, free of charge, to any person obtaining a copy
~ of this software and associated documentation files (the "Software"), to deal
~ in the Software without restriction, including without limitation the rights
~ to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
~ copies of the Software, and to permit persons to whom the Software is
~ furnished to do so, subject to the following conditions:
~
~ The above copyright notice and this permission notice shall be included in all
~ copies or substantial portions of the Software.
~
~ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
~ IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
~ FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
~ AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
~ LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
~ OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
~ SOFTWARE.
*/}}

{{- $name := "docker-auth-rootbundle-tls" }}
{{- if and .Values.tls.enabled .Values.tls.selfSigned }}
{{- $ca := genCA "docker-auth-registry-ca" 365 }}
{{- $cert := genSignedCert .Values.ingress.host nil (list .Values.ingress.host) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ $name }}
    namespace: {{ .Release.Namespace }}
    annotations:
        {{- include "registry.auth.annotations" (dict "context" .) | nindent 8 }}
    labels:
        {{- include "registry.auth.labels" . | nindent 8 }}
type: kubernetes.io/tls
data:
    tls.crt: {{ include "common.secrets.lookup" (dict "secret" $name "key" "tls.crt" "defaultValue" $cert.Cert "context" $) }}
    tls.key: {{ include "common.secrets.lookup" (dict "secret" $name "key" "tls.key" "defaultValue" $cert.Key "context" $) }}
    ca.crt: {{ include "common.secrets.lookup" (dict "secret" $name "key" "ca.crt" "defaultValue" $ca.Cert "context" $) }}
{{- else if and .Values.tls.enabled .Values.tls.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: {{ $name }}
    namespace: {{ .Release.Namespace }}
    annotations:
        {{- include "registry.auth.annotations" (dict "context" .) | nindent 8 }}
    labels:
        {{- include "registry.auth.labels" . | nindent 8 }}
spec:
    secretName: {{ printf "%s-crt" $name }}
    commonName: {{ printf "%s.%s.svc.%s" (include "registry.auth.fullname" .) .Release.Namespace .Values.global.clusterDomain }}
    issuerRef:
        name: {{ coalesce .Values.tls.certManager.issuer .Values.tls.certManager.clusterIssuer }}
        kind: {{ ternary "Issuer" "ClusterIssuer" (not (empty .Values.tls.certManager.issuer)) }}
        group: {{ .Values.tls.certManager.group }}
    {{- with .Values.tls.certManager.organizations }}
    subject:
        organizations:
            {{ toYaml . | nindent 8 }}
    {{- end }}
    dnsNames:
        - "*.{{ .Release.Namespace }}"
        - "*.{{ .Release.Namespace }}.svc"
        - "*.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
        - "*.{{ include "registry.auth.fullname" . }}"
        - "*.{{ include "registry.auth.fullname" . }}.{{ .Release.Namespace }}"
        - "*.{{ include "registry.auth.fullname" . }}.{{ .Release.Namespace }}.svc"
        - "*.{{ include "registry.auth.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
    privateKey:
        algorithm: {{ .Values.tls.certManager.privateKey.algorithm }}
        size: {{ .Values.tls.certManager.privateKey.size | int }}
    duration: {{ .Values.tls.certManager.duration }}
    renewBefore: {{ .Values.tls.certManager.renewBefore }}
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ $name }}
    namespace: {{ .Release.Namespace }}
    annotations:
        {{- include "registry.auth.annotations" (dict "context" .) | nindent 8 }}
    labels:
        {{- include "registry.auth.labels" . | nindent 8 }}
type: kubernetes.io/tls
data:
    tls.crt: {{ .Values.tls.secret.tlsCrt | b64enc }}
    tls.key: {{ .Values.tls.secret.tlsKey | b64enc }}
    ca.crt: {{ .Values.tls.secret.caCrt | b64enc }}
{{- end }}
